base_url = "https://www.liamgallagher.dev"
compile_sass = true
build_search_index = false
minify_html = true
generate_feed = true
author = "Liam Gallagher"

[markdown]
highlight_code = true
highlight_theme = "ayu-mirage"

[extra]
